version: "3.8"

services:
  db:
    image: ibmcom/db2
    privileged: true
    ports:
    - 50000:50000
    volumes:
    - ./database:/database
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2inst1
      DBNAME: stack
